# shellcheck shell=tcsh
# AUTOMATICALLY GENERATED by `shtab`

${preamble}

complete ${prog} \
        'c/--/(${optionals_double_str})/' \
        'c/-/(${optionals_single_str})/' \
        ${optionals_special_str} \
        'p/*/()/'
